### ISSUE TITLE
chore: global overview of core ui pages. opinions?

### ISSUE THREAD

**Issue by vonderklaas** [tinyglob/tinyglob-website#5]
## Home Page

- **Interactive Map Interface**
Upon opening the app, users are greeted with an interactive map interface displaying continents and countries.
Each continent and country is represented by clickable bubbles indicating the number of job openings available in that location.

- **Search Bar**
An integrated search bar allows users to search for specific continents, countries, or job titles.

- **Featured Job Posts**
Showcase a selection of featured job posts or trending opportunities on the home page.

## Continent Page

- **Map Overview**
Display a detailed map of the selected continent or country with bubbles representing job openings.
Users can zoom in/out and pan across the map to explore different regions.

- **Job Filters**
Provide filters to refine job search results by industry, salary range, experience level, etc.

- **List of Job Openings**
Show a list of job openings with brief previews, including job title, company name, and location.
Each job listing can be clickable, leading to the detailed job description page.

## Job Details Page

- **TikTok-Style Job Previews**
Integrate short video previews of job posts alongside traditional job listings for a visually engaging experience.
Showcase the TikTok-style video job post uploaded by the employer, providing insights into company culture and job role.

- **Detailed Job Description**
Present a detailed description of the job including responsibilities, requirements, qualifications, and benefits.

- **Apply Button**
Include a prominent "Apply Now" button for users to easily apply for the job directly within the app.

## User Profile Page

- **Profile Information**
Allow users to create and manage their profiles, including personal details, skills, experience, and preferences.

- **Saved Jobs**
Provide a section for users to save their favorite job listings for future reference.

- **Application History**
Display a history of past job applications with status updates and notifications.

**Comment by garbalau-github** [comment]
@martiniucanastasia need your opinion on these pages and ui flows.

**Comment by garbalau-github** [comment]
I LOOK FOR JOB / I HIRE?
